name: doh_kyaung_taw
description: Doh_Kyaung_Taw application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider: ^4.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/

  fonts:
    - family: MyanmarSanpya
      fonts:
        - asset: assets/fonts/MyanmarSanpya.ttf
    - family: ArtTrue
      fonts:
        - asset: assets/fonts/trueArt.ttf


  uses-material-design: true

